[project]
name = "akari-proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "maturin>=1.10.1",
    "pip>=25.3",
    "setuptools>=80.9.0",
]
