[project]
name = "akari-proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "brotli>=1.2.0",
    "maturin>=1.10.1",
    "pip>=25.3",
    "psutil>=7.1.3",
    "requests>=2.32.5",
    "setuptools>=80.9.0",
]
